### ISSUE TITLE
Tableau Features 3.4.7

### ISSUE THREAD

**Issue by KlippL** [mschermann/data_viz_reader#753]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L474-L476

There are many useful references that will be helpful when learning Tableau and currently there is only one line describing an instruction about Tableau. I think having a much larger section as a reference guide when practicing Tableau will be helpful.

**Comment by ttussing** [comment]
Tableau should definitely be included in many since it is so widely used. We can certainly use it to expand upon which visualizations are possible. Additionally, many of the issues the other visualization types have raised, were solved in tableau

**Comment by KlippL** [comment]
I'm thinking that more should be written about Tableau in Chapter 3.3 Data Visualization Tools. There is a list of topics needed to be covered and then there is a random paragraph in chaper 5.10 about tableau. All should be consolidated and expanded.

**Comment by Vidya313** [comment]
I agree the Tableau section requires more content and restructuring to consolidate the existing topics. I would like to contribute to fixing this issue in the upcoming weeks.

**Comment by KlippL** [comment]
Currently, under section 3.4.7 this is listed

The following tips for Tableau are still missing:

1. Running totals
2. Common Baseline
3. Weighted averages
4. Moving average
5. Grouping by aggregates
6. Different years comparison
7. Appending excel sheets
8. Bar chart totals
9. Fixed axis when re-drawing charts
10. Auto-fitting screen behavior depending on data selection

___________
We should start adding these as well as something on merging vs. blending data and more basic ideas in Tableau. I already moved 3.4.7.1 Using Shapes as Filters in Tableau When Your Fields Are Measures from chapter 5, so the rest of the information we add should be in the form of new headers using #### to indicate a new subsection of 3.4.7.2 and so on.

**Comment by KlippL** [comment]
Here is what I found on blending data in Tableau:
https://onlinehelp.tableau.com/current/pro/desktop/en-us/multiple_connections.htm

For this week I am planning on adding a section on #### Multiple Data Sources

- Cross Database Join 
- Data Blending

**Comment by KlippL** [comment]
I made a new branch for us to work on this in:
Tableau-Features-3.4.7-#753

**Comment by Vidya313** [comment]
For this week I am planning to further expand the section #### Multiple Data Sources.
- Using Unions 
- Tableau Extracts

**Comment by KlippL** [comment]
@ttussing this is where your project proposal should go... the projects page is something different. 

I added it back in here just in case you need to take a look at it...

The Tableau section in Fundamentals needs a lot of work given how significant the tool is. The section already recommended a list of items (to be removed) that should be added:

1. Running Totals
2. Common Baseline
3. Weighted Averages
4. Moving average
5. Grouping by aggregates 
6. Different years of comparison
7. Appending excel sheets
8. Bar chart totals
9. Fixed axis when re-drawing charts
10. Auto-fitting screen behavior depending on data selection

We can add some or all of these along with others. The branch is "Tableau-Features-3.4.7

**Comment by KlippL** [comment]
This week I am writing a section on getting started with tableau:
- dimensions
- measures
- creating a view in sheets
- refining your view

**Comment by KlippL** [comment]
This week I'm writing a section on grouping data in Tableau:
- Examples of how grouping is useful 
- How to create a group 
- Including an "other" group
- Color view using a group

**Comment by KlippL** [comment]
This week I wrote about how to make sets in tableau including the different types of sets and how to make them.
